server:
  port: 8080
  servlet:
    encoding:
      force: true
spring:
  mvc:
    format:
      date-time: iso
  profiles:
    active: local
    group:
      local:
        - local-db
#        - redis
      test:
        - test-db
#        - redis









